name: Deploy Template AWS (EKS)

on:
  workflow_call:
    inputs:
      aws-region:
        description: "AWS Region"
        required: true
        type: string
      eks-cluster-name:
        description: "Nome do cluster EKS"
        required: true
        type: string
      manifest-path:
        description: "Pasta/arquivo de manifests"
        required: true
        type: string
      namespace:
        description: "Namespace Kubernetes"
        required: true
        type: string
      deployment-name:
        description: "Deployment para rollout"
        required: true
        type: string
      container-name:
        description: "Nome do container no deployment"
        required: true
        type: string
      image-uri:
        description: "Se informado, faz kubectl set image"
        required: false
        type: string
        default: ""
      rollout-timeout:
        description: "Timeout rollout"
        required: false
        type: string
        default: "180s"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (Access Keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name "${{ inputs.eks-cluster-name }}" \
            --region "${{ inputs.aws-region }}"

      - name: Apply manifests
        run: |
          kubectl apply -f "${{ inputs.manifest-path }}"

      - name: Set image (optional)
        if: ${{ inputs.image-uri != '' }}
        run: |
          kubectl set image deployment/${{ inputs.deployment-name }} \
            -n ${{ inputs.namespace }} \
            ${{ inputs.container-name }}=${{ inputs.image-uri }}

      - name: Rollout status
        run: |
          kubectl rollout status deployment/${{ inputs.deployment-name }} \
            -n ${{ inputs.namespace }} \
            --timeout=${{ inputs.rollout-timeout }}

      - name: Show ingress
        run: |
          kubectl get ingress -n ${{ inputs.namespace }} -o wide || true
